### ISSUE TITLE
ARM (Apple M3 Pro) support on MacOS + Docker?

### ISSUE THREAD

**Issue by s3w47m88** [dvankley/firefly-plaid-connector-2#117]
Will there be support via Docker on ARM (Apple M3 Pro) processors? Is there a workaround in the mean time?

**Comment by dvankley** [comment]
You should be able to enable using Rosetta to run x64 images on Docker for Mac. There's a "Use Rosetta for x86_64/amd64 emulation on Apple Silicon" option in Docker Settings->General.

Alternately, you can run the connector directly using Java.

I don't currently have any plans to provide a multiplatform image (largely due to the above workarounds), but if you'd like to submit a PR to update the Github Action that invokes the [OCI builder](https://docs.spring.io/spring-boot/gradle-plugin/packaging-oci-image.html) to add the `arm` platform, feel free.

**Comment by s3w47m88** [comment]
Strange. I do have Rosetta enabled in settings.

Do you have any docs regarding using Java?

I may circle back around to using OCI to add arm. Thank you!
